# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gstiedem <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/24 15:33:49 by gstiedem          #+#    #+#              #
#    Updated: 2019/04/21 16:45:22 by gstiedem         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=libft.a
CC=gcc
CFLAGS=-Wall -Werror -Wextra
SRC=ft_atoi.c ft_bzero.c ft_freeargv.c ft_isalnum.c ft_isalpha.c ft_isascii.c\
	ft_isdigit.c ft_isin.c ft_islower.c ft_isprint.c ft_isspace.c ft_isupper.c\
	ft_itoa.c ft_lstadd.c ft_lstdel.c ft_lstdelone.c ft_lstiter.c ft_lstmap.c\
	ft_lstnew.c ft_memalloc.c ft_memccpy.c ft_memchr.c ft_memcmp.c ft_memcpy.c\
	ft_memdel.c ft_memmove.c ft_memset.c ft_memvchr.c ft_pow.c ft_putchar.c\
	ft_putchar_fd.c ft_putendl.c ft_putendl_fd.c ft_putnbr.c ft_putnbr_fd.c\
	ft_putstr.c ft_putstr_fd.c ft_strcat.c ft_strchr.c ft_strclr.c ft_strcmp.c\
	ft_strcpy.c ft_strdel.c ft_strdup.c ft_strequ.c ft_striter.c ft_striteri.c\
	ft_strjoin.c ft_strlcat.c ft_strlen.c ft_strmap.c ft_strmapi.c ft_strncat.c\
	ft_strncmp.c ft_strncpy.c ft_strnequ.c ft_strnew.c ft_strnlcpy.c\
	ft_strnlen.c ft_strnstr.c ft_strrchr.c ft_strsplit.c ft_strstr.c\
	ft_strsub.c ft_strtrim.c ft_strvchr.c ft_tolower.c ft_toupper.c ft_wc.c
OBJ = $(SRC:.c=.o)
INCL_DIR := ../../include
INCLUDE := $(INCL_DIR)/libft.h
INC_FLAG := -I$(INCL_DIR)

all: $(NAME)

$(NAME): $(OBJ) $(INCLUDE)
	@ar -rc $(NAME) $(OBJ)
	@ranlib $(NAME)

clean:
	@rm -f $(OBJ)

fclean: clean
	@rm -f $(NAME)

re: fclean all

%.o: %.c
	$(CC) $(CFLAGS) $(INC_FLAG) -c $< -o $@
